/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.old-api.conf 14476 2006-04-18 17:36:51Z hardaker $
 */
#ifndef MULTICASTCONFIG_H
#define MULTICASTCONFIG_H

/*
 * function declarations 
 */
void            init_multicastConfig(void);
FindVarMethod   var_multicastConfig;
FindVarMethod   var_igmpSnoopingMembTable;
WriteMethod     write_igmpSnoopingEnable;
WriteMethod     write_igmpSnoopingAgeTime;
WriteMethod     write_igmpSnoopingFastleaveEnable;

#endif                          /* MULTICASTCONFIG_H */
