var  g_lang_info = {
    type:
    [
        "English",
        "简体中文"
    ],
    info:
    [
        {
            cmn:
            {
                innerHTML:
                {
                    txt_step:"Loading..."
                },
                option_text:
                {
                    enable_disable:
                    [
                        "Enable",
                        "Disable"
                    ],
                    disable_enable:
                    [
                        "Disable",
                        "Enable"
                    ]
                },
                value:
                {
                    bt_refresh:"Refresh",
                    bt_create:"Create",
                    bt_del:"Delete",
                    bt_apply:"Apply"
                },
                js_string:
				{
                    set_ok:"successfully",
				    set_failed:"Fail",
                    enable_disable:
                    [
                        "Enable",
                        "Disable"
                    ],
                    disable_enable:
                    [
                        "Disable",
                        "Enable"
                    ],
				    set_outofrange:"Out of range"
				}
            }
        },
        
        {
            cmn:
            {
                innerHTML:
                {
                    txt_step:"载入中..."
                },
                option_text:
                {
                    enable_disable:
                    [
                        "激活",
                        "禁用"
                    ],
                    disable_enable:
                    [
                        "禁用",
                        "激活"
                    ]
                },
                value:
                {
                    bt_refresh:"刷新",
                    bt_create:"创建",
                    bt_del:"删除",
                    bt_apply:"应用"
                },
                js_string:
				{
                    set_ok:"成功",
                    set_failed:"失败",
                    enable_disable:
                    [
                        "激活",
                        "禁用"
                    ],
                    disable_enable:
                    [
                        "禁用",
                        "激活"
                    ],
				    set_outofrange:"超出范围"
				}
            }
        }
    ]
};


