#ifndef __IROS_VERSION_H
#define __IROS_VERSION_H


// definitions for versions for iros releases
// major, minor and patch numbers should be provided explicitly either here or
// use gcc -D option when building the target.
// BuildId is normally automatically generated by building tools.
#if !defined(IROS_VER_MAJOR)
#define IROS_VER_MAJOR "6"
#endif
#if !defined(IROS_VER_MINOR)
#define IROS_VER_MINOR "15"
#endif
#if !defined(IROS_VER_REVISION)

#ifdef HAVE_OOB_MGMT
#define IROS_VER_REVISION "1"
#else
#define IROS_VER_REVISION "1"
#endif

#endif

#if !defined(IROS_VER_BUILD_ID)
#define IROS_VER_BUILD_ID "15"
#endif

#if defined(IROSBOOT)
// loaders
#if defined(CYG_HAL_ARM_IMST_OLT)
// OLT loaders
#define  IROS_OLT_LOADER_VER_MAJOR  IROS_VER_MAJOR
#define  IROS_OLT_LOADER_VER_MINOR  IROS_VER_MINOR
#define  IROS_OLT_LOADER_VER_REVISION  IROS_VER_REVISION
#define  IROS_OLT_LOADER_VER_BUILD  IROS_VER_BUILD_ID
#else
// ONU loaders
#define  IROS_ONU_LOADER_VER_MAJOR  IROS_VER_MAJOR
#define  IROS_ONU_LOADER_VER_MINOR  IROS_VER_MINOR
#define  IROS_ONU_LOADER_VER_REVISION  IROS_VER_REVISION
#define  IROS_ONU_LOADER_VER_BUILD  IROS_VER_BUILD_ID
#endif
#else
// apps
#if defined(CYG_HAL_ARM_IMST_OLT)
// OLT apps
#define  IROS_OLT_APP_VER_MAJOR  IROS_VER_MAJOR
#define  IROS_OLT_APP_VER_MINOR  IROS_VER_MINOR
#define  IROS_OLT_APP_VER_REVISION  IROS_VER_REVISION
#define  IROS_OLT_APP_VER_BUILD  IROS_VER_BUILD_ID
#elif defined(CYG_HAL_ARM_IMST_ONU)
// ONU apps
#define  IROS_ONU_APP_VER_MAJOR  IROS_VER_MAJOR
#define  IROS_ONU_APP_VER_MINOR  IROS_VER_MINOR
#define  IROS_ONU_APP_VER_REVISION  IROS_VER_REVISION
#define  IROS_ONU_APP_VER_BUILD  IROS_VER_BUILD_ID
#else
#define  IROS_SC_VER_MAJOR  IROS_VER_MAJOR
#define  IROS_SC_VER_MINOR  IROS_VER_MINOR
#define  IROS_SC_VER_REVISION  IROS_VER_REVISION
#define  IROS_SC_VER_BUILD  IROS_VER_BUILD_ID
#endif
#endif

typedef struct {
    unsigned int          build_id;
    unsigned int          major;
    unsigned int          minor;
    unsigned int          revision;
} loader_version_t;


#endif /* __IROS_VERSION_H */

