#!/usr/bin/perl  
#  sortf [colpos]

use strict;

my $colpos;

if (defined($ARGV[0])) {
	$colpos = $ARGV[0];
}

my @Lines = <STDIN>;

ColGet(\@Lines);

exit;

sub ColGet {
	my $pLines = shift;
	my (@fields, @KeyArray, $Line, $i, $j, $LineTmp, $KeyVal);
	for $Line (@{$pLines}) {
		$LineTmp = $Line;
		$LineTmp =~ s/^\s*//g;  # del leading space
		@fields = split /\s+/, $LineTmp;
		if (defined($colpos)) {
			printf("%s\n", $fields[$colpos]);
		} else {
			printf("%s\n", $fields[$#fields]);
		}
	}
}












